language: node_js
node_js:
  - "0.10.24"
before_install: 
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install mocha
  - bower install
  - gem install compass
#install: npm install
before_script: grunt test
